### ISSUE TITLE
Faute de frappe

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/normes-graphiques#1]
Il y a une toute petite faute de frappe sur le site compagnon : 

https://github.com/zestedesavoir/normes-graphiques/blob/760de8e61db551b50af186bb228230ae8ee77e02/companion/src/components/Shadows.vue#L50

On y voit `incude` au lieu de `include`.

**Comment by AmauryCarrade** [comment]
ono

merci !
